permalinks: pretty
# Setup
title:            HRay
tagline:          'Penetration Tester'
description:      'A twenty-something Penetration Tester'
url:              http://hray.co.uk/
baseurl:          http://hray.co.uk/

author:
  name:           'Hugh Raynor'
  url:            https://twitter.com/HughRaynor

paginate:         5

comments:
  provider: disqus
disqus: 
  short_name: hray