# Permalinks
permalink:        pretty

# Setup
title:            Hugh Raynor
tagline:          'Penetration Tester'
description:      'A twenty-something British Penetration Tester'
url:              http://hray.co.uk
baseurl:          /

author:
  name:           'Hugh Raynor'
  url:            https://twitter.com/HughRaynor

paginate:         5