permalink: pretty
# Setup
title:            HRay
tagline:          'A twenty-something penetration tester'
description:      'Hugh Raynor is a twenty-something cyber-security consultant from Bristol, England. A holder of the GIAC GICSP and CHECK Team Member status, Hugh is interested in Industrial Control Systems and infrastructure security assessments.'
url:              https://hray.co.uk
locale:           en_GB

author:
  name:           'Hugh Raynor'
  url:            https://twitter.com/HughRaynor
  twitter:        HughRaynor

paginate:         5

comments:
  provider: disqus
disqus: 
  short_name: hray

plugins:
  - jekyll-seo-tag

include:
  [".well-known"]
