permalink: pretty
# Setup
title:            HRay
tagline:          'Penetration Tester'
description:      'A twenty-something Penetration Tester'
url:              https://hray.co.uk/

author:
  name:           'Hugh Raynor'
  url:            https://twitter.com/HughRaynor
  twitter:        HughRaynor

paginate:         5

comments:
  provider: disqus
disqus: 
  short_name: hray

plugins:
  - jekyll-seo-tag